### ISSUE TITLE
Intensity of the processed image

### ISSUE THREAD

**Issue by meifeng005** [LeonieZ/ACCEPT#1]
Hi, I am from CBB working with Guofeng.
I was using ACCEPT to analyse CTCs. 
Here are some questions I would like to clarify some doubts about the ACCEPT
1: is the intensity of the processed image absolute intensity or relative intensity (like raw intensity - noise level)
2. I notice that the maximum intensity and mean intensity is the same, is this how the software supposed to be?
Look forward to your reply! 
![image](https://user-images.githubusercontent.com/35591683/35138458-a2418734-fd29-11e7-8145-07a1426196e9.png)

**Comment by LeonieZ** [comment]
Hi,

1. the intensity is relative to the median of the background (so the median intensity of everything that is not segmented).
2. that the max value coincides with the mean intensity was a bug in an older version. I corrected it, it will be uploaded with the next commit.


On 19. Jan 2018, at 08:01, meifeng005 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I am from CBB working with Guofeng.
I was using ACCEPT to analyse CTCs.
Here are some questions I would like to clarify some doubts about the ACCEPT
1: is the intensity of the processed image absolute intensity or relative intensity (like raw intensity - noise level)
2. I notice that the maximum intensity and mean intensity is the same, is this how the software supposed to be?
Look forward to your reply!
[image]<https://user-images.githubusercontent.com/35591683/35138458-a2418734-fd29-11e7-8145-07a1426196e9.png>
