### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PathfinderP** [LeonieZ/ACCEPT#2]
Hi! 

I just installed the ACCEPT but when i double click on it to open the following message appears: Output argument ''sampleNames'' (and maybe others) not assigned during call to ''IO.available.samples''. Error in => ACCEPT.m at line 44.

What should i do to solve the problem?

Thank you in advance!
Periklis

**Comment by PathfinderP** [comment]
started <<<< ACCEPT version: 1.0.0-beta
15:43:59: >>>> Session stopped <<<< 
Output argument "sampleNames" (and maybe others) not assigned during call to "IO.available_samples".

Error in SampleList/updated_input_path (line 124)


Error in SampleList/set.inputPath (line 67)


Error in gui_main (line 45)


Error in ACCEPT (line 44)

MATLAB:unassignedOutputs
Error writing to output stream.
iostream stream error

**Comment by LeonieZ** [comment]
Hi,

It seems that in the folder which was saved as the last input folder you chose no samples can be found. If you browse to “C:\Users\user_name\AppData\Local\Temp\ user_name \mcrCache9.3” (number at the end can be different) and search for a file called “LatestSettings.mat” and delete it will open again. Alternatively you can also delete the whole ACCEPT folder in that file location.

When using it again, make sure to select as input folder, the folder that contains a folder for each sample, not the sample folder itself!

**Comment by PathfinderP** [comment]
Hi!
Great thanks! it works.
when i load the input folder, it asks me for manual channel entry. Should i
tell the channels and wavelengths of the protocol i used or i just close
that window?

Thank you again

*Katopodis Periklis*

HNZW146, Heinz Wolff Building
Institute of Environment, Health and Societies
Department of Life Sciences
Brunel University London, UK

LinkedIn <https://www.linkedin.com/in/periklis-katopodis-568544ab/>

**Comment by LeonieZ** [comment]
Hi,

Which sample processor did you choose? If you select the Full Detection it shouldn’t ask you for manual entries. And what kind of sample (from which microscope system) did you use as input?

Leonie

**Comment by PathfinderP** [comment]
Dear Leonie,

I am using images from Image Stream exported from AMNIS software in .tiff
format. And yes, on full detection it s not asking for manual entry but it
s prossesing the images for ever. Maybe can't recognise the tiffs from this
software(?)

Thank you for your replies,
Periklis

*Katopodis Periklis*

HNZW146, Heinz Wolff Building
Institute of Environment, Health and Societies
Department of Life Sciences
Brunel University London, UK

LinkedIn <https://www.linkedin.com/in/periklis-katopodis-568544ab/>

**Comment by LeonieZ** [comment]
Dear Perikli,

In general it should be possible to process your tiff images, but you should copy the file that I attached in your folder and adjust it to your channel names. And the images for all channels should be separate (with the corresponding name of the marker that you fill in the excel file somewhere in the filename, e.g. 001_PE.tif, 001_DAPI.tif, 001_PerCP.tif) and not stitched to one large image. If your scan consists of around 200 images it should take about 20-30 minutes dependent on the amount of cells found.

Leonie

**Comment by 1006478712** [comment]
Dear Leonie,

I am using images from Image Stream exported from EVOS FL 2 in .tiff
format.  However when I use ACCEPT, it is prossesing the images for ever. What is the required image format?

Thank you for your replies,
Yi Wang

**Comment by LeonieZ** [comment]
Dear Yi Wang, 

probably it is also not recognizing your channel names correctly, take the attached document, adjust it to your channel names and save it as .csv in the folder with all your images. And as I said above, the images should **not** be stitched to one large image covering the full surface recorded. 

[customChannels.txt](https://github.com/LeonieZ/ACCEPT/files/1802268/customChannels.txt)
