### ISSUE TITLE
Images processing error

### ISSUE THREAD

**Issue by Wistar1308** [LeonieZ/ACCEPT#4]
Hello,
    I tried to analysize the cell images. But it seemed not to be processed. I wondered I set it wrongly.
    Do someone check my setting and give me some help?
    Thank you!!!
[T.zip](https://github.com/LeonieZ/ACCEPT/files/2204360/T.zip)
![prtscr](https://user-images.githubusercontent.com/41325962/42858885-8d387aa4-8a83-11e8-810b-86c444774fba.PNG)

**Comment by LeonieZ** [comment]
Hi, the Marker Characterization processor you chose is used to analyze prescored CTCs but this requires that you either have images exported from the CellSearch system or used our ICY Plugin to first manually score CTCs. To detect every cell in the image choose the Full Detection processor. 
Also note that there is a minimum amount of images per channel, how many images do you have per sample?

**Comment by Wistar1308** [comment]
Hello Leonie,
    I tried it in Full Detection and it didn't work, either. :(
    There are 3 images in each sample: DAPI, CTCs and WBCs. Ther are all in gray scale image.
    Are 3 images still less than the minimum?
    Thank you.

**Comment by LeonieZ** [comment]
Yes, the assumption we made that we are not analyzing single images but full automated scans of the whole imaging area normally resulting in more than 100 images per channels so currently the minimum is 100 tiffs for all channels together. But if you are using it through Matlab and still want to test it you can open the Default.m file in ACCEPT/input_output/Loaders and change the second line in 'can_load_this_folder' (at the bottom of the script) to [tifDir,tifdirFound]=Loader.find_dir(path,'tif',3);

**Comment by Wistar1308** [comment]
Ok~

Thank you so much!!!
